/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FAQEntry = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addFAQEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addInitialFAQEntries' : IDL.Func([], [], []),
  'getAllFAQEntries' : IDL.Func([], [IDL.Vec(FAQEntry)], ['query']),
  'getFAQAnswer' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'incrementVisitorCount' : IDL.Func([], [IDL.Nat], []),
  'submitMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FAQEntry = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addFAQEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addInitialFAQEntries' : IDL.Func([], [], []),
    'getAllFAQEntries' : IDL.Func([], [IDL.Vec(FAQEntry)], ['query']),
    'getFAQAnswer' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'incrementVisitorCount' : IDL.Func([], [IDL.Nat], []),
    'submitMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };